spring.application.name=Mini-store-app


spring.datasource.url=jdbc:mysql://localhost:3306/Mini_store_app
spring.datasource.username=root
spring.datasource.password=1234567890
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
server.port = 8081

